# wrangler.toml
name = "cookiecloud-worker"
main = "src/index.js"
compatibility_date = "2023-10-30"

# D1 数据库绑定
# 当部署时，这个绑定会让你的 Worker 代码可以通过 env.DB 访问数据库
[[d1_databases]]
binding = "DB"
database_name = "cookiecloud-db"
database_id = "" # 这个ID在首次创建数据库时会自动生成，但部署脚本会处理它
preview_database_id = ""